# Generated by Django 5.0.7 on 2024-11-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='agent_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='weather',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
